version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    restart: always
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      # Prevents the host node_modules from clobbering the image's
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_MODE: real
    ports:
      - 3000:3000
  api:
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      FLASK_ENV: ${FLASK_ENV:-development}
      WAIT_HOSTS: db:5432
    ports:
      - 6000:5000

volumes:
  postgres: {}
